# Generated by Django 2.2.7 on 2019-12-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('first_working', models.CharField(max_length=8)),
                ('last_working', models.CharField(max_length=8)),
                ('first_off', models.CharField(max_length=8)),
                ('last_off', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=float("inf"))),
                ('price', models.IntegerField(default=0)),
                ('route', models.CharField(max_length=4096)),
                ('begin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='begin', to='booking.Station')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end', to='booking.Station')),
            ],
        ),
    ]
