# Generated by Django 3.0 on 2019-12-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_neighbor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='first_off',
        ),
        migrations.RemoveField(
            model_name='line',
            name='first_working',
        ),
        migrations.RemoveField(
            model_name='line',
            name='last_off',
        ),
        migrations.RemoveField(
            model_name='line',
            name='last_working',
        ),
        migrations.AddField(
            model_name='station',
            name='first_off',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='station',
            name='first_working',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='station',
            name='last_off',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='station',
            name='last_working',
            field=models.CharField(default='', max_length=8),
        ),
    ]
