# Generated by Django 3.0 on 2019-12-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191205_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbor',
            old_name='next',
            new_name='next_station',
        ),
        migrations.RenameField(
            model_name='neighbor',
            old_name='prev',
            new_name='prev_station',
        ),
    ]
