# Generated by Django 3.0 on 2019-12-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20191205_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station',
            name='name',
        ),
        migrations.AddField(
            model_name='line',
            name='line_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='line', to='booking.Line'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='next_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_station', to='booking.Station'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='prev_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prev_station', to='booking.Station'),
        ),
    ]
