# Generated by Django 3.0 on 2019-12-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20191205_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbor',
            old_name='prev_station_id',
            new_name='prev_station',
        ),
    ]
