# Generated by Django 3.0 on 2019-12-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20191205_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighbor_line', to='booking.Line'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='next_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighbor_next_station', to='booking.Station'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='prev_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighbor_prev_station', to='booking.Station'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighbor_station', to='booking.Station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='begin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='begin_station', to='booking.Station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_station', to='booking.Station'),
        ),
    ]
