# Generated by Django 2.2.7 on 2019-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20191206_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
