# Generated by Django 2.2.7 on 2019-12-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_route_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='first_off',
        ),
        migrations.RemoveField(
            model_name='station',
            name='first_working',
        ),
        migrations.RemoveField(
            model_name='station',
            name='last_off',
        ),
        migrations.RemoveField(
            model_name='station',
            name='last_working',
        ),
    ]
